- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
  - -c
  - |
    API_URL=$(gcloud run services describe veriface-api --region us-central1 --format='value(status.url)')
    gcloud run deploy veriface-ui \
      --image us-central1-docker.pkg.dev/$PROJECT_ID/veriface/veriface-ui:$COMMIT_SHA \
      --region us-central1 \
      --platform managed \
      --allow-unauthenticated \
      --service-account veriface-runner@${PROJECT_ID}.iam.gserviceaccount.com \
      --port 8080 \
      --set-env-vars API_BASE_URL=$API_URL,UI_BUILD_SHA=$COMMIT_SHA \
      --memory 1Gi \
      --cpu 2
options:
  logging: CLOUD_LOGGING_ONLY
